#!/bin/bash
colors=(${color_hex0} ${color_hex1} ${color_hex2} ${color_hex3} ${color_hex4} ${color_hex5} ${color_hex6} ${color_hex7}
         ${color_hex8} ${color_hex9})
lines=(12 13 14 15 16 17 18 19 20 21 22)
hashchar='#'
semichar=';'
path='/home/greg/.config/rofi/themes/'

for i in ${!colors[*]}
do
    line=${lines[$i]}
    trancolor=${colors[$i]}
    color=$(echo $trancolor | cut -c4-9)
    sed -i "${line}"'s/.*/    color'"${i}"':'"${hashchar}${color}${semichar}"'/' "$path"'theme_template.rasi' 
done

rm ${path}theme.rasi
cp ${path}theme_template.rasi ${path}theme.rasi
#sed 's/.*/    var: '$hashchar$color$semichar/ $path"theme_template.rasi" > $path"theme.rasi"
