#!/bin/bash
unset hex0
unset hex1
unset hex2
unset hex3
unset hex4
unset hex5
unset hex6
unset hex7
unset hex10

source ~/.cache/wal/colors.sh


colors=(${color0} ${color1} ${color2} ${color3} ${color4} ${color5} ${color6} ${color7} ${color8} 
${color9} ${color10} ${color11} ${color12} ${color13} ${color14})

lines=(12 13 14 15 16 17 18 19 20 21 22)
semichar=';'
path='/home/greg/.config/rofi/themes/'

for i in ${!lines[*]}
do
    line=${lines[$i]}
    trancolor=${colors[$i]}
    color=$(echo $trancolor)
    sed -i "${line}"'s/.*/    color'"${i}"':'"${color}${semichar}"'/' "$path"'theme_template.rasi' 
done

rm ${path}theme.rasi
cp ${path}theme_template.rasi ${path}theme.rasi
#sed 's/.*/    var: '$hashchar$color$semichar/ $path"theme_template.rasi" > $path"theme.rasi"
