#!/bin/sh

base="https://aur.archlinux.org/packages/"
i=1
pkg_count=$(pacman -Qm | wc -l)
echo "all" >> packages
while [ "$i" -ne "$pkg_count" ]; do
	package=$(pacman -Qm | head -"$i" | tail -1)
	name=$(echo "$package" | cut -d' ' -f1)
	local=$(echo "$package" | cut -d' ' -f2)
	current=$(curl --silent "$base$name" | grep "Package Details:" | cut -d ' ' -f4 | cut -d '<' -f1)
	if [ "$local" != "$current" ]; then
		echo "$name - Local $local // Current $current" >> packages
	fi
	i=$((i + 1))
done

update_pkg_count=$(wc -l packages | cut -d' ' -f1)
echo Select a package to update:
nl packages
n=""
while true; do
	echo "Select Package: "
	read n 
	if [ "$n" -eq "$n" ] && [ "$n" -gt 0 ] && [ "$n" -le "$update_pkg_count" ]; then
		break
	fi
done
value="$(sed -n "${n}p" packages)"

if [ "$value" = "all" ]; then
	while IFS= read -r line; do
		if [ "$line" != "all" ]; then
			aur $(echo "$line" | cut -d ' ' -f1)
		fi
	done < packages
else
	aur $(echo "$value" | cut -d' ' -f1)
fi
rm /home/greg/scripts/packages
