#!/bin/sh

BASE="https://aur.archlinux.org/packages/"
i=1
PKG_COUNT=$(pacman -Qm | wc -l)
echo "all" >> packages
while [ "$i" -ne "$PKG_COUNT" ]; do
	PACKAGE=$(pacman -Qm | head -"$i" | tail -1)
	NAME=$(echo "$PACKAGE" | cut -d' ' -f1)
	LOCAL=$(echo "$PACKAGE" | cut -d' ' -f2)
	CURRENT=$(curl --silent https://aur.archlinux.org/packages/"$NAME" | grep "Package Details:" | cut -d ' ' -f4 | cut -d '<' -f1)
	if [ "$LOCAL" != "$CURRENT" ]; then
		#echo "$NAME" - Local "$LOCAL" // Current "$CURRENT" 
		echo "$NAME - Local $LOCAL // Current $CURRENT" >> packages
	fi
	i=$((i + 1))
done

UPDATE_PKG_COUNT=$(wc -l packages | cut -d' ' -f1)
echo Select a package to update:
nl packages
n=""
while true; do
	read -p 'Select Package: ' n
	if [ "$n" -eq "$n" ] && [ "$n" -gt 0 ] && [ "$n" -le "$UPDATE_PKG_COUNT" ]; then
		break
	fi
done
value="$(sed -n "${n}p" packages)"

if [ "$value" = "all" ]; then
	while IFS= read -r line; do
		if [ "$line" != "all" ]; then
			aur $(echo "$line" | cut -d ' ' -f1)
		fi
	done < packages
else
	aur $(echo "$value" | cut -d' ' -f1)
fi
rm /home/greg/scripts/packages
